language: java
sudo: false
jdk:
  - oraclejdk7
env:
  - profile="java-mms.1-0" phase="test" pl=""
  - profile="java-mms.1-0" phase="verify" pl="-pl systests"
  - profile="java-mms.0-10" phase="verify" pl="-pl systests"
  - profile="java-mms.0-9" phase="verify" pl="-pl systests"
script: "mvn ${phase} -P${profile} ${pl} -Dtest.overridden.properties=${TRAVIS_BUILD_DIR}/test-profiles/apache-ci.test.overridden.properties"
